
# Syntax highlighting
highlighter:         rouge

# Permalinks
permalink:           /:title
relative_permalinks: false

# Setup
timezone:            Europe/Rome
locale:              it_it
name:				         'uBC Magazine'
title:               'site title'
tagline:             'tagline'
description:         'description'
url:                 'http://lupigi.github.io/ubcmagazine'
rss:                 rss feed url
baseurl:             '/ubcmagazine/'
baseurl_posts_img:   '/ubcmagazine/assets/images/posts/'
baseurl_featured_img: '/ubcmagazine/assets/images/hero/'
baseurl_featured_thumbnail: '/ubcmagazine/assets/images/thumbnail/'
baseurl_javascripts: '/ubcmagazine/assets/javascripts/'
icon:                '/ubcmagazine/assets/img/icon.png' # [best 300px X 300px]
disqus:              disqus_shortname # get it on https://disqus.com/admin/

#author:
#  name:           	 your name
#  url:            	 your site url
#  facebook:          username
#  twitter:           username
#  google_plus:       username
#  linkedin:          username
#  dribbble:          username
#  pinterest:         username
#  kiva:              username

#fb_admins:           your facebook profile id
#fb_appid:            your facebook app id

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
